version: '3.8'

services:
  # Laravel Application with MySQL Database
  app-db:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tms
    depends_on:
      - db
    command: sh -c "sleep 30 && php artisan migrate && php artisan serve --host=0.0.0.0 --port=8000"

  # MySQL Database
  db:
    image: mysql:8.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tms
